# visualization_task:
#   description: >
#     데이터가 주어지면 사용자가 알아보기 쉽게 시각화하는 도구입니다.
#   expected_output: >
#     주어진 데이터에 대한 시각화된 그래프
#   agent: visualization_agent

# news_collectiong_task:
#   description: >
#     주어진 토픽에 대한 가장 관련성 있는 뉴스를 검색합니다.
#   expected_output: >
#     주어진 토픽에 대한 관련성 높은 뉴스 5개
#   agent: news_collector_agent

# summarization_task:
#   description: >
#     주어진 뉴스 정보들을 요약합니다.
#   expected_output: >
#     주어진 뉴스의 중요한 정보만을 담은 200자 이내의 요약
#   agent: summary_agent

# search_task:
#   description: > 
#     최신 AI 및 데이터사이언스의 연구 동향을 찾고 내용을 가져오세요.
#     Key trends와 획기적인 기술, 산업의 잠재성을 함께 기술하세요.
#     당신의 대답은 반드시 full analysis report여야 합니다.
#   expected_output: >
#     AI와 데이터사이언스의 최신 연구 동향에 대한 상세한 분석 리포트
#   agent: researcher

# write_task:
#   description: >
#     제공된 정보들을 바탕으로 최신 AI 트렌드를 강조하는 블로그 포스트를 작성하세요.
#     당신의 포스트는 유용한 정보를 담고 있어야 하며, AI에 대해 잘 모르는 일반인도 이해할 수 있어야 합니다.
#     최종 답변은 반드시 2개 이상의 paragraph를 담고 있는 완전한 블로그 포스트여야 합니다.
#   expected_output: >
#     일반인도 이해하기 쉬운 AI 트렌드 블로그 포스트
#   agent: writer

# analyze_task:
#   description: >
#     테이블 데이터를 분석하고, 데이터 요약 및 통찰을 생성하는 작업입니다. 
#     이 작업에서는 통합된 테이블 데이터를 바탕으로 목표 주가, 변동성 등의 주요 정보를 요약합니다.
#   expected_output: >
#     증권사별 기업 분석 요약 (예: 목표 주가 평균, 최대값, 최소값) 및 통합된 테이블 데이터
#   agent: table_analysis_agent

# convert_task:
#   description: >
#     사용자가 제공한 마크다운 형식의 테이블 데이터를 pandas 데이터프레임으로 변환하는 작업입니다. 
#     데이터의 정리 및 표준화도 포함됩니다.
#   expected_output: >
#     데이터프레임 형식으로 변환된 테이블 데이터
#   agent: table_conversion_agent

# visualize_task:
#   description: >
#     분석된 데이터를 기반으로 막대그래프, 꺾은선그래프 등 시각화를 생성하는 작업입니다.
#     사용자가 쉽게 데이터를 이해할 수 있도록 시각적 자료를 제공합니다.
#   expected_output: >
#     생성된 그래프와 그래프의 파일 경로 (예: PNG 또는 JPEG 포맷) 출력
#   agent: table_visualization_agent



# visualization_task:
#   description: >
#     주어진 데이터와 요청에 맞게 시각화 작업을 수행합니다.
#     사용자가 요청한 그래프, 테이블 또는 데이터프레임을 시각적으로 표현합니다.
#   goal: >
#     데이터를 시각적으로 표현하여 사용자가 쉽게 이해할 수 있도록 합니다.
#   expected_output: >
#     요구 사항에 맞는 시각화된 그래프, 테이블 또는 데이터프레임
#   agent: graph_agent


# table_task:
#   description: >
#     주어진 데이터를 테이블 형식으로 변환하여 시각화합니다.
#     표의 스타일과 필요한 옵션들을 조정하여 출력합니다.
#   goal: >
#     테이블 형식으로 데이터를 시각적으로 표현하여 사용자가 쉽게 파악할 수 있도록 합니다.
#   expected_output: >
#     요구 사항에 맞는 시각화된 테이블
#   agent: table_agent

# dataframe_task:
#   description: >
#     주어진 데이터프레임을 받아 원하는 형식으로 시각화하여 결과를 출력합니다.
#   goal: >
#     데이터프레임을 시각적으로 표현하여 중요한 인사이트를 도출합니다.
#   expected_output: >
#     요구 사항에 맞는 시각화된 데이터프레임
#   agent: dataframe_agent

retrieval_task:
  description: >
    데이터를 검색하고 Retrieval 결과를 수집하여 Table, Graph, Context 분석가에게 전달하세요.
    결과는 분석에 필요한 필수 정보가 포함되어야 합니다.
  expected_output: >
    분석가들이 사용할 수 있는 Retrieval 결과 데이터
  agent: retrieval_scheduler

table_conversion_task:
  description: >
    주어진 Table 데이터를 pandas의 Dataframe으로 변환하세요.
    변환 결과는 가독성이 좋아야 하며 분석에 적합해야 합니다.
  expected_output: >
    pandas Dataframe 형식의 변환된 Table 데이터
  agent: table_changer

table_analysis_task:
  description: >
    변환된 Table 데이터를 분석하고 유용한 정보를 정리하세요.
    분석 결과는 데이터의 주요 인사이트를 포함해야 합니다.
  expected_output: >
    Table 데이터를 분석하여 도출된 주요 인사이트
  agent: table_analyzer

graph_analysis_task:
  description: >
    주어진 Graph 이미지를 분석하고 유용한 정보를 도출하세요.
    분석 결과는 그래프에서 파악된 주요 트렌드와 데이터를 포함해야 합니다.
  expected_output: >
    Graph 분석 결과 및 주요 트렌드
  agent: graph_analyzer

context_analysis_task:
  description: >
    제공된 Context 데이터를 분석하여 유용한 정보를 정리하세요.
    분석 결과는 사용자에게 바로 전달할 수 있을 만큼 명확해야 합니다.
  expected_output: >
    Context 데이터를 분석한 주요 정보 요약
  agent: context_analyzer

visualization_task:
  description: >
    분석된 데이터를 바탕으로 적합한 시각화 자료를 생성하세요.
    시각화 자료는 직관적이고 사용자 친화적이어야 합니다.
  expected_output: >
    분석 결과를 보여주는 직관적인 시각화 자료
  agent: visualizer

code_execution_task:
  description: >
    분석가가 제공한 코드를 실행하고, 실행 결과를 반환하여 시각화 작업을 진행하거나 결과를 사용자에게 전달합니다.
  expected_output: >
    실행된 코드의 결과물, 예: 시각화된 차트, 분석된 데이터, 보고서 등
  agent: code_executor

answer_task:
  description: >
    사용자 질문에 적절한 데이터를 바탕으로 이해하기 쉬운 답변을 작성하세요.
    최종 답변은 고객 친화적이며 정확해야 합니다.
  expected_output: >
    사용자의 질문에 대한 정확하고 명확한 답변
  agent: final_answer_agent
