# visualization_task:
#   description: >
#     데이터가 주어지면 사용자가 알아보기 쉽게 시각화하는 도구입니다.
#   expected_output: >
#     주어진 데이터에 대한 시각화된 그래프
#   agent: visualization_agent

# news_collectiong_task:
#   description: >
#     주어진 토픽에 대한 가장 관련성 있는 뉴스를 검색합니다.
#   expected_output: >
#     주어진 토픽에 대한 관련성 높은 뉴스 5개
#   agent: news_collector_agent

# summarization_task:
#   description: >
#     주어진 뉴스 정보들을 요약합니다.
#   expected_output: >
#     주어진 뉴스의 중요한 정보만을 담은 200자 이내의 요약
#   agent: summary_agent

retrieve_task:
  description: >
    사용자의 질의에 대해 Vector DB에서 관련 정보를 검색하세요.
    표와 이미지의 경로를 함께 제공해야 합니다.
  expected_output: >
    질의와 관련된 정확한 정보 및 데이터, 표와 이미지 경로 포함
  agent: retriever

code_generation_task:
  name: "code_generation_task"
  description: "초기 쿼리와 테이블 데이터를 기반으로 시각화 코드를 생성"
  input:
    - "search_query"
    - "table_data"
  output: "generated_code"

code_execution_task:
  name: "code_execution_task"
  description: "생성된 코드를 실행하여 시각화 이미지를 생성하고 저장"
  input: "generated_code"
  output: "visualization_image_path"