
visualization_task:
  description: >
    데이터가 주어지면 사용자가 알아보기 쉽게 시각화하는 도구입니다.
  expected_output: >
    주어진 데이터에 대한 시각화된 그래프
  agent: visualization_agent

news_collectiong_task:
  description: >
    주어진 토픽에 대한 가장 관련성 있는 뉴스를 검색합니다.
  expected_output: >
    주어진 토픽에 대한 관련성 높은 뉴스 5개
  agent: news_collector_agent

summarization_task:
  description: >
    주어진 뉴스 정보들을 요약합니다.
  expected_output: >
    주어진 뉴스의 중요한 정보만을 담은 200자 이내의 요약
  agent: summary_agent