final_answer_task:
  description: >
    이미지 분석가 : {image_result}
    본문 분석가 : {context_result}
    테이블 분석가 : {table_result}
    주어진 세가지 답변에 대해 최종 답변을 도출하세요.
    만약 각 분석가가 도출한 답변에서 출처, 경로가 있다면 반드시 표기하세요.
    이미지, 본문, 테이블 분석가의 답변을 나누지 말고 하나의 답변으로 출력하세요.
    이미지의 출처, 생성된 이미지 경로는 반드시 답변을 다 끝내고 마지막에 모아서 전체 이름을 표기하세요.
  expected_output: >
    질문에 대한 최종 답변
    이미지 출처, 생성된 이미지의 경로들
    
  agent: final_answerman