final_answer_task:
  description: >
    이미지 분석가 : {image_result}
    본문 분석가 : {context_result}
    테이블 분석가 : {table_result}
    주어진 세가지 답변에 대해 최종 답변을 도출하세요.
    만약 각 분석가가 도출한 답변에서 출처, 경로가 있다면 반드시 표기하세요.
    출처, 경로는 반드시 답변을 다 끝내고 마지막에 모아서 전체 이름을 표기하세요.
  expected_output: >
    [출력형식]
    질문에 대한 최종 답변
    [참조 이미지의 경로]
    [생성된 이미지 이름]
  agent: final_answerman