final_answer_task:
  description: >
    이미지 분석가 : {image_result}
    본문 분석가 : {context_result}
    테이블 분석가 : {table_result}
    주어진 답변들을 종합하여 질문에 대한 최종 답변을 도출하세요.
    만약 생성된 이미지의 경로가 있다면 반드시 표기하세요.
    받은 답변들을 하나의 답변으로 종합하여 출력하세요.
    생성된 이미지 경로는 반드시 답변을 다 끝내고 마지막에 모아서 전체 경로를 표기하세요.
  expected_output: >
    [출력 형식]
    질문에 대한 최종 답변\n
    [생성된 이미지 경로]\n
    - 생성된 이미지의 경로
    
  agent: final_answerman